agenciafmd/starter

resources/js/frontend.js
- Essa funcao gera automaticamente os direitos reservados com ano e pode ser utilizada no front. Utilizando a classe js-copyright-container quando estiver dentro do footer.
=> feat(direitos reservados): Adiciona funcao

resources/sass/components/_accordion.scss, resources/sass/frontend.scss, resources/sass/frontend/_variables.scss
- Para o arquivo padrao de variaveis
=> fix(accordion): Altera localizacao das variaveis

package.json, resources/js/frontend-imports.js, resources/sass/vendors/_vendors.scss
- Adicionado library no package.json e alterado a chamada nos arquivos
frontend-imports.js e _vendors.scss que estava incorreta
=> fix(library): Adiciona biblioteca wow

package.json
- Como frontender, preciso atualizar a versão do jQuery para arrumar um
problema de vulnerabilidade da lib
=> feat(pacote): jquery e browser-sync

packages/agenciafmd/frontend/src/resources/views/html/tema.blade.php, resources/js/frontend.js, resources/sass/components/_spinners.scss
- Como frontender, preciso de uma função/classe adicionar o atributo
disabled e um ícone de loading para evitar que o usuário fique clicando
descontroladamente e enviando formulários desnecessários.
=> feat(formulario): Adicionar trava de botão submit  após clique

resources/sass/components/_icons.scss, resources/sass/frontend/_variables.scss, resources/sass/vendors/_tiny-slider.scss
Como frontender, preciso adicionar visibility-hidden ao tns-item,
para evitar problemas com acessibilidade.
=> chore(tns) adiciona visibility hidden ao tns-item

packages/agenciafmd/frontend/src/resources/views/html/master.blade.php, packages/agenciafmd/frontend/src/resources/views/master.blade.php, resources/sass/components/_icons.scss, resources/sass/frontend/_variables.scss
Como Frontender preciso criar classes de variações de tamanho de ícones para padronizar no projeto.
=> fix(icons) adiciona classes de tamanhos de ícones para padronizarmos

packages/agenciafmd/frontend/src/resources/views/html/tema.blade.php, resources/js/frontend.js
-Como Frontender preciso que a função de animação esteja isolada para que eu possa reaproveitar em outras partes do código ou em diferentes aplicações.
=> feat(frontendjs) Isolar função de scroll animate para reaproveitar

packages/agenciafmd/frontend/src/resources/views/html/index.blade.php, packages/agenciafmd/frontend/src/resources/views/pages/index.blade.php
Como o novo frontend da equipe, senti a necessidade de colocar algumas frases que fazem sentido para mim e remover frases de antigos funcionários
=> feat(frases na index): Adiciona frases do Renan e remove antigos

resources/js/frontend.js
- Eu como frontend vi a necessidade de uma função para fazer o envio do datalayer quando eu precisar clicar em um link.
=> feat(datalayer): Adiciona nova função

packages/agenciafmd/frontend/src/resources/views/master.blade.php, packages/agenciafmd/frontend/src/resources/views/partials/fonts-preload.blade.php, resources/js/frontend.js, resources/sass/_styles.scss, resources/sass/bootstrap/_variables.scss, resources/sass/components/_icons.scss, resources/sass/components/_links.scss, resources/sass/frontend.scss, resources/sass/frontend/_reboot.scss, resources/sass/frontend/_typography.scss, resources/sass/frontend/_variables.scss, webpack.mix.js
Como frontend, senti a necessidade de corrigir algumas questões e alterar outras que já foram discutidas com o time
=> feat(sugestões): Adiciona correções e algumas alterações previamente alinhadas

package-lock.json, package.json, resources/js/components/lax.js, resources/js/frontend-imports.js
Como frontend, senti a necessidade de adicionar um plugin que facilite as animações de acordo com o scroll
=> feat(lax.js): Adiciona lax.js ao projeto

resources/js/frontend.js
Como frontend, senti a necessidade de corrigir um erro que desabilitava todos os buttons da página ao invés de só aquele do form que foi submitado
=> fix(form buttons): Corrige falha que desabilitava todos os buttons da página

resources/js/frontend.js
- Quando fui utilizar o starter, reparei que o nome estava incorreto, segue commit para corrigir
=> fix(função setupSmoothScroll): Ajusta o nome da classe

packages/agenciafmd/frontend/src/resources/views/components/fmd-link.blade.php, packages/agenciafmd/frontend/src/resources/views/html/index.blade.php, packages/agenciafmd/frontend/src/resources/views/html/partials/footer.blade.php, packages/agenciafmd/frontend/src/resources/views/pages/index.blade.php, packages/agenciafmd/frontend/src/resources/views/partials/footer.blade.php
- (Quase) Todas as vezes esqueco do target="_blank", por que não criar um
componente pra não esquecer mais?
=> feat(F&MD Link): Adiciona componente de link para o https://fmd.ag

resources/js/frontend-imports.js, resources/js/frontend.js, resources/js/helpers/data-layer.js
Link para a documentação atualizada
https://github.com/agenciafmd/starter/wiki/Funcionalidades-JS-Disponiveis#utilit%C3%A1rios-de-data-layer
=> feat(data layer): Separa responsabilidade do arquivo principal de JS

packages/agenciafmd/frontend/src/resources/views/partials/message.blade.php
- Em contato com o Matheus do mkt, foi solicitado um novo padrão para envio dos dados, onde foi alterado nesse commit
=> feat(datalayer): Ajusta datalayer paramentro event para form

packages/agenciafmd/frontend/src/resources/views/components/swiper-buttons.blade.php
Eu como frontend vejo necessidade de criar um componente de swiper buttons
=> feat(Swiper Buttons): Criar componente para os botões do swiper

packages/agenciafmd/frontend/src/resources/views/html/partials/header.blade.php, public/vendor/livewire/manifest.json
Os links do header não tem os atributos de acessibilidade (aria-label e title)
Adiciona o atributos "aria-label" e "title" aos links do header
=> chore(Header): Adiciona acessibilidade aos links do header no /html

resources/js/components/fmd-header.js, resources/sass/components/_navbar.scss
No commit anterior [1f58adc](https://github.com/agenciafmd/starter/commit/1f58adc8e578ed584d449b24c1f9e0d8d20f3de0), foi adicionado para executar o evento de resize e com isso a altura do header era modificada a cada momento quando tinha alteração na resolução da página.
Acontece que quando está na versão mobile, no momento que a barra de endereço é escondida, pelo comportamento padrão, o evento de resize era acionado, e com isso o tamanho do header era modificado. Dessa forma acontecia de ocorrer problemas de remontar o offcanvas em cima header na abertura do menu offcanvas.
Foi aplicado uma validação para não executar o resize na versão mobile. Então está se …
=> fix(fmd-header): Valida execução do resize quando estiver na versão mobile

public/manifest.json, resources/js/pwa/manifest.json
Atualmente o PWA possui as propriedades de **background_color**, **theme_color** com valores que não correspondem ao tema utilizado no projeto. E também não possui o suporte do ícone mstile-150x150 para png, pois o mesmo esta duplicado com o formato webp.
Implementa correção das propriedades **background_color**, **theme_color** com valores corretos e ajusta estrutura de mstile-150x150 duplicada para png.
=> chore(propriedades): implementa correção de propriedades importantens

resources/js/frontend-imports.js, resources/js/frontend.js
Import de função e dependência share api sendo a mesma não utilizada em todos os projetos.
Comenta import e chamada de função de share api para evitar código desnecessário.
=> chore(share api): comenta import e função de setupShareApi

resources/sass/components/_navbar.scss
Na abertura do menu mobile, o offcanvas abria um pouco acima do local de fato
O offcanvas é exibido de forma elegante, feito o cálculo com variável do projeto
=> feat(fmd-header): Ajusta o calculo do padding para o offcanvas

packages/agenciafmd/frontend/src/resources/views/html/master.blade.php, packages/agenciafmd/frontend/src/resources/views/master.blade.php
Atualmente não possuímos a tag e com isso alguns elementos de telefone acabam tendo um comportamento indesejado como se fosse links de telefone e isso acontece no safari.
Adiciona nova tag em arquivos da masters para evitar bugs indesejados em textos de telefones.
=> feat(metatag): adiciona nova metatag para form-detection telephone

packages/agenciafmd/frontend/src/resources/views/components/icon.blade.php, packages/agenciafmd/frontend/src/resources/views/components/picture.blade.php, packages/agenciafmd/frontend/src/resources/views/partials/fonts-preload.blade.php
- [x ] A mensagem de commit segue o padrão do Commit Amigão: [https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit](https://github.com/BeeTech-global/bee-stylish/blob/master/commits/README.md)
- [ x] feat (nova funcionalidade)
atualmente chamamos os arquivos que não vem das mix files,
Nosso Fonts-preload e nossos componentes de icon e picture agora irão vir acompanhados de um id gerado pelo mix apenas para paginas que não são da /html
=> Update icon picture component

packages/agenciafmd/frontend/src/resources/views/components/pdf.blade.php
Foi criado um novo componente para facilitarmos a inserção de pdf ao projeto
=> New pdf component

packages/agenciafmd/frontend/src/resources/views/html/partials/header.blade.php
Atualmente temos um código muito extenso que na qual podemos aproveitar as vantagens do php para enxugarmos o código e deixar mais simples de ver e entender.
Implementa refactor de estrutura de links para deixar o código do header mais simples e fácil de entender.
=> refactor(estrutura): implementa refactor de estrutura do header

.gitignore
Atualmente, os arquivos build/assets e build/manifest.json estão sendo ignorados no versionamento.
Atualiza o .gitignore para permitir o versionamento do diretório /build, evitando problemas em homologação e produção.
=> feat(gitignore): remove build

config/filesystems.php, config/google-fonts.php
Atualmente, o fonts.css está utilizando URL absoluta, conforme configurado.
Adiciona novo filesystem disk para fontes e ajusta config/google-fonts.php para utilizar URL relativa.
=> feat(config): adiciona filesystem disk para fontes

composer.json
=> fix(composer json): atualiza mudando o google fonts de lugar
